name: Upload Markdown

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pandas gspread oauth2client PyYAML

      - name: Restore credentials.json from secret
        run: |
          echo "${{ secrets.GS_CREDENTIALS_BASE64 }}" | base64 -d > credentials.json
          echo "‚úÖ credentials.json Â∑≤ÈÇÑÂéü"

      - name: Download Google Sheet and convert to Markdown
        run: python convert_and_commit.py
        
        env:
        SPREADSHEET_ID: "1yXofSNohNOnZFUGT6n0jz8FggSiAtGwITt4YMLoVLSs"
        SHEET_NAME: "ÂØ©Ê†∏ÈÄöÈÅé"
  
      - name: Push to GitHub
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .
          git commit -m "Auto update GitBook content" || echo "üü° Nothing to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
